# Generated by Django 5.2.5 on 2025-08-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('setor', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMaquina', models.CharField(max_length=25)),
                ('numPatrimonio', models.CharField(max_length=8)),
                ('model', models.CharField(max_length=10)),
                ('setor', models.CharField(max_length=8)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaboradoes')),
            ],
        ),
    ]
