# Generated by Django 5.2.5 on 2025-08-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinas',
            old_name='model',
            new_name='modelo',
        ),
    ]
